services:
    bot-prod:
        build:
            context: .
            args:
                    NODE_ENV: production
        container_name: court-bot-prod
        environment:
              - NODE_ENV=production
        env_file:
            - .env.production
        depends_on:
            - db
        restart: unless-stopped
        volumes:
            - ./private:/usr/src/bot/private:ro
            - ./src/api/db/migrations:/usr/src/bot/migrations:ro
        networks:
                - court-bot-network

    bot-dev:
        build:
            context: .
            args:
                    NODE_ENV: development
        container_name: court-bot-dev
        environment:
              - NODE_ENV=development
        env_file:
            - .env.development
        depends_on:
            - db
        restart: unless-stopped
        volumes:
            - ./private:/usr/src/bot/private:ro
            - ./src/api/db/migrations:/usr/src/bot/migrations:ro
        networks:
                - court-bot-network

    db:
        image: postgres:16 # Or a newer version
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
                - court-bot-network

networks:
    court-bot-network:
        driver: bridge

volumes:
  db_data:
